version: "3.8"
services:
  db:
    image: postgres:13.1
    container_name: postgres_container_gp
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-d", "postgres", "-U", "root" ]
      timeout: 45s
      interval: 10s
      retries: 10
    restart: always
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=password
    volumes:
      - week2_db
    ports:
      - 5432:5432
  adminer:
    image: adminer
    container_name: adminer_container_gp
    restart: always
    ports:
      - 8080:8080
volumes:
  week2_db:
